import { useEffect } from "react"
import { useParams } from "react-router-dom"
import { motion } from 'framer-motion'
import Navbar from '../components/Navbar/Navbar'
import Footer from '../components/Footer/Footer'
import { useAuth } from '../context/AuthContext'
import AppLayout from '../layouts/AppLayout'
import styles from './Legal.module.css'

const LAST_UPDATED = 'May 3, 2026'
const CONTACT_EMAIL = 'hello@smeltr.app'
const COMPANY = 'SMELTR'
const DOMAIN = 'smeltr.vercel.app'

const PRIVACY_SECTIONS = [
  {
    title: '1. Information We Collect',
    content: [
      'Account information: name, email address, and password when you sign up.',
      'Profile data: goals, wake time, shift type, and preferences you provide during onboarding.',
      'Usage data: daily habit completions, discipline log entries, trade journal entries, gratitude entries, and reflections.',
      'Payment information: we do not store your card details. Payments are processed by Paystack (for African users) and Polar (for international users). We only receive confirmation of payment status.',
      'Device and technical data: IP address, browser type, and general location for region detection to route you to the correct payment provider.',
    ]
  },
  {
    title: '2. How We Use Your Information',
    content: [
      'To provide and operate the SMELTR service.',
      'To power your AI daily debrief — your habit data and reflection are sent to the Claude API (Anthropic) to generate personalised coaching responses.',
      'To detect your region and present the appropriate payment method.',
      'To send transactional emails — account confirmation, payment receipts.',
      'To improve the product based on aggregated, anonymised usage patterns.',
    ]
  },
  {
    title: '3. Data Storage',
    content: [
      'Your data is stored in Google Firebase Firestore, hosted on Google Cloud infrastructure.',
      'Payment processing is handled by Paystack (Nigeria/Africa) and Polar (international). We do not store payment card information.',
      'AI debrief responses are generated by Anthropic\'s Claude API. Your reflection text is sent to Anthropic for processing and the response is stored in your account.',
    ]
  },
  {
    title: '4. Data Sharing',
    content: [
      'We do not sell your personal data to third parties.',
      'We share data only with service providers necessary to operate the platform: Google Firebase, Anthropic (Claude API), Paystack, and Polar.',
      'We may disclose data if required by law or to protect the rights and safety of our users.',
    ]
  },
  {
    title: '5. Data Retention',
    content: [
      'Your data is retained for as long as your account is active.',
      'If you delete your account, your personal data will be deleted within 30 days.',
      'Anonymised, aggregated data may be retained indefinitely for product improvement.',
    ]
  },
  {
    title: '6. Your Rights',
    content: [
      'Access: you can request a copy of your personal data at any time.',
      'Correction: you can update your profile information from the Profile page.',
      'Deletion: you can request account deletion by emailing us at ' + CONTACT_EMAIL,
      'Portability: you can request an export of your data.',
    ]
  },
  {
    title: '7. Cookies',
    content: [
      'We use essential cookies and local storage to maintain your session and remember your theme preference.',
      'We do not use advertising or tracking cookies.',
    ]
  },
  {
    title: '8. Children',
    content: [
      'SMELTR is not intended for users under the age of 16. We do not knowingly collect data from children.',
    ]
  },
  {
    title: '9. Changes to This Policy',
    content: [
      'We may update this policy from time to time. We will notify you of significant changes via email or an in-app notice.',
    ]
  },
  {
    title: '10. Contact',
    content: [
      'For privacy questions or data requests, contact us at ' + CONTACT_EMAIL,
    ]
  },
]

const TERMS_SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    content: [
      'By creating an account or using SMELTR, you agree to these Terms of Service. If you do not agree, do not use the service.',
      'These terms apply to all users of SMELTR, including free and Pro subscribers.',
    ]
  },
  {
    title: '2. The Service',
    content: [
      'SMELTR is a personal accountability and habit tracking web application that includes AI-powered coaching, a trade journal, and discipline logging tools.',
      'We reserve the right to modify, suspend, or discontinue any part of the service at any time with reasonable notice.',
    ]
  },
  {
    title: '3. Account Responsibilities',
    content: [
      'You are responsible for maintaining the security of your account and password.',
      'You must provide accurate information when creating your account.',
      'You must be at least 16 years old to use SMELTR.',
      'You are responsible for all activity that occurs under your account.',
    ]
  },
  {
    title: '4. Acceptable Use',
    content: [
      'You agree not to use SMELTR for any unlawful purpose.',
      'You agree not to attempt to reverse engineer, hack, or compromise the security of the platform.',
      'You agree not to use the AI coaching feature to generate harmful, illegal, or abusive content.',
      'Violation of these terms may result in immediate account termination.',
    ]
  },
  {
    title: '5. Subscriptions and Payments',
    content: [
      'SMELTR offers a free tier and a Pro subscription at $7/month or $60/year (USD) for international users, and ₦7,000/month or ₦60,000/year (NGN) for Nigerian/African users.',
      'Payments are processed by Paystack (African users) or Polar (international users). By subscribing you agree to their respective terms.',
      'Subscriptions renew automatically unless cancelled before the renewal date.',
      'You can cancel your subscription at any time from your Profile page. You retain Pro access until the end of the current billing period.',
      'We do not offer refunds except where required by applicable law.',
    ]
  },
  {
    title: '6. AI Coaching',
    content: [
      'The AI coach feature is powered by Anthropic\'s Claude API. Responses are generated by an AI model and should not be considered professional medical, psychological, financial, or legal advice.',
      'Do not use the AI coach as a substitute for professional help. If you are in crisis, please contact a qualified professional or crisis service.',
      'By using the AI coach you acknowledge that your reflection text is sent to Anthropic for processing.',
    ]
  },
  {
    title: '7. Intellectual Property',
    content: [
      'SMELTR and all its content, features, and functionality are owned by us and protected by applicable intellectual property laws.',
      'Your personal data — habits, reflections, trades — belongs to you. We do not claim ownership of your content.',
    ]
  },
  {
    title: '8. Disclaimer of Warranties',
    content: [
      'SMELTR is provided "as is" without warranties of any kind, express or implied.',
      'We do not guarantee that the service will be uninterrupted, error-free, or that results from using the service will meet your expectations.',
    ]
  },
  {
    title: '9. Limitation of Liability',
    content: [
      'To the maximum extent permitted by law, SMELTR shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.',
      'Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.',
    ]
  },
  {
    title: '10. Governing Law',
    content: [
      'These terms are governed by the laws of the Federal Republic of Nigeria.',
      'Any disputes shall be resolved through good-faith negotiation, or if necessary, through the appropriate courts in Nigeria.',
    ]
  },
  {
    title: '11. Changes to Terms',
    content: [
      'We may update these terms from time to time. Continued use of SMELTR after changes constitutes acceptance of the new terms.',
      'We will notify you of material changes via email.',
    ]
  },
  {
    title: '12. Contact',
    content: [
      'For questions about these terms, contact us at ' + CONTACT_EMAIL,
    ]
  },
]

const LegalContent = ({ type }: { type: 'privacy' | 'terms' }) => {
  const isPrivacy = type === 'privacy'
  const sections = isPrivacy ? PRIVACY_SECTIONS : TERMS_SECTIONS
  const title = isPrivacy ? 'Privacy Policy' : 'Terms of Service'

  return (
    <div className={styles.content}>
      <motion.div
        className={styles.header}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
      >
        <p className={styles.label}>// Legal</p>
        <h1 className={styles.title}>{title.toUpperCase()}</h1>
        <p className={styles.meta}>
          Last updated: {LAST_UPDATED} · {COMPANY} · {DOMAIN}
        </p>
        {isPrivacy ? (
          <p className={styles.intro}>
            This Privacy Policy explains how SMELTR collects, uses, and protects
            your personal information. We are committed to handling your data
            responsibly and transparently.
          </p>
        ) : (
          <p className={styles.intro}>
            These Terms of Service govern your use of SMELTR. Please read them
            carefully. By using SMELTR you agree to be bound by these terms.
          </p>
        )}
      </motion.div>

      {sections.map((section, i) => (
        <motion.div
          key={section.title}
          className={styles.section}
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: i * 0.04 }}
        >
          <h2 className={styles.sectionTitle}>{section.title}</h2>
          <ul className={styles.list}>
            {section.content.map((item, j) => (
              <li key={j} className={styles.item}>{item}</li>
            ))}
          </ul>
        </motion.div>
      ))}

      <div className={styles.footer}>
        <p>Questions? Email us at <a href={`mailto:${CONTACT_EMAIL}`} className={styles.link}>{CONTACT_EMAIL}</a></p>
      </div>
    </div>
  )
}

const Legal = () => {
  const { type } = useParams<{ type: string }>()
  const { user } = useAuth()
  const legalType = (type === 'privacy' || type === 'terms') ? type : 'privacy'

  useEffect(() => {
    window.scrollTo(0, 0)
  }, [type])

  if (user) {
    return (
      <AppLayout>
        <LegalContent type={legalType} />
      </AppLayout>
    )
  }

  return (
    <>
      <Navbar />
      <div style={{ paddingTop: '80px' }}>
        <LegalContent type={legalType} />
      </div>
      <Footer />
    </>
  )
}

export default Legal
